name: basic workflow

# on: push
  # pull_request:
  #   branches:
  #     - main
on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    env:
      WORKING_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: install python version
        uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python-version }} 
      
      - name: grant permissions to scripts
        run: |
          cd $WORKING_DIR
          echo "working directory: $PWD"
          chmod +x ./scripts/venv.sh
          chmod +x ./scripts/run_tests.sh
          chmod +x ./app/test_main.py
          chmod +x ./scripts/summarize_results.sh
      
      
      - name: install dependencies and set up environment
        run: source ./scripts/venv.sh
      
      - name: run tests
        run: ./scripts/run_tests.sh

      - name: summarize results
        if: always()
        run: |
          cd $WORKING_DIR && ls -l logs/
          echo "Summarizing test results..."
          ./scripts/summarize_results.sh > ./test_summary.txt
          cat ./test_summary.txt
      
      - name: Upload Test Summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-summary-${{matrix.python-version}}
          path: ./test_summary.txt  

    #   - name: Upload Test logs
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: test-logs
    #       path: ./logs/
