name: secrets and env workflow

on: [workflow_dispatch]

jobs:
    repo-secrests-and-vars:
      runs-on: ubuntu-24.04
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: print repo variables
          run: |
                echo "Printing Repository variable"
                echo "MY_API_KEY: ${{ vars.MY_API_KEY }}"
    
    enviornment-secrests-and-vars:
      runs-on: ubuntu-24.04
      environment: stagging
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: print repo variables
          run: |
                echo "Printing Repository variable"
                echo "MY_API_KEY: ${{ vars.MY_API_KEY }}"
    